### ISSUE TITLE
requirement.txt

### ISSUE THREAD

**Issue by gchonpo** [techmn/elgcnet#1]
Hello, may I ask if you can provide requirement. txt? I couldn't find it in the code. Thank you very much

**Comment by techmn** [comment]
Hi, You can install the following libraries
https://pytorch.org/get-started/previous-versions/#linux-and-windows-21

```
torch==1.11.0
timm==0.4.12
cuda==10.2
opencv-python
scikit-learn
numpy
fvcore
pillow
tqdm
```
